---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: minio
  name: minio
spec:
  replicas: 1
  selector:
    app: minio
    deploymentconfig: minio
  template:
    metadata:
      labels:
        app: minio
        deploymentconfig: minio
    spec:
      containers:
        - env:
            - name: MINIO_ACCESS_KEY
              value: defaultkey
            - name: MINIO_SECRET_KEY
              value: defaultkey
          image: >-
            jwiii/openshift-minio
          name: minio
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /minio/health/ready
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /minio/health/live
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /export
            name: export
          - mountPath: /root/.minio/
            name: minio-config-dir
      volumes:
        - name: export
          persistentVolumeClaim:
            claimName: minio
        - emptyDir: {}
          name: minio-config-dir
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
spec:
  ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
    deploymentconfig: minio
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: minio
  name: minio
spec:
  port:
    targetPort: 9000-tcp
  to:
    kind: Service
    name: minio
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio
  name: minio
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
